services:
  backend:
    build: ./mern-demo/server
    network_mode: host
    env_file:
      - ./mern-demo/server/.env

  frontend:
    build: ./mern-demo/client
    network_mode: host
    depends_on:
      - backend